apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: YOUR_NAMESPACE
  ownerReferences: YOUR_VALUE
  labels: YOUR_VALUE
  labels: YOUR_VALUE
spec:
  containers:
  - name: nginx_container
    image: nginx
